media:
  input: public/media
  output: /media
content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    filename: "{title}.md"
    fields:
    - { name: title, label: Title, type: string, required: true }
    - { name: body, label: Body, type: rich-text, required: true }
settings:
  hide: true
  